### ISSUE TITLE
Blog format changed unexpectedly for the worse

### ISSUE THREAD

**Issue by lmeggiolaro** [landportal/drupal#100]
The view of blogs changed suddenly. Now the title is repeated THREE times, very small, very big, and medium size, the picture is to the left, and all of the text forced to the right. The posting date now appears under the second title. The related terms are squished together, with no space between them.

**Comment by lisettemeij** [comment]
I deleted the extra title (I don't see the third??) and put the publication date to the bottom.

I didn't change the left-right display, because someone probably did that with a particular idea in mind (and it's how the rest of the website is displayed, so makes sense, no?)

The display about the concepts are as they are on the whole website, I agree that it does not look great. Something we can change with a new design probably. Or changing the CSS for the tags.

See attached screenshot:
![screen shot 2016-07-11 at 11 19 23](https://cloud.githubusercontent.com/assets/6312043/16725859/982e0e7a-4759-11e6-8436-163cc1c32b8f.png)

**Comment by lisettemeij** [comment]
I also put back the "submitted by" line today instead of the "posted on" date (since submitted by also seemed to include the posting date).

Didn't change the two columns set up, because that seems to be done in code. Can we retrace how that changed somehow? For the people working on the front end, it would be nice to know when / why these things are changing :)

**Comment by jcr** [comment]
The teaser view now benefits from the new style but lack some 'teaser' text.
On the blog page, there should be some space between the image and the tags.

**Comment by jcr** [comment]
I am now closing this.
While the general style can surely be improve there is no 'major' issue with the blog page display in the new version.
