### ISSUE TITLE
Change filter in view "Library resources by provider" to allow OR conditions

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#103]
(From @lisettemeij conversation)
The view "Library resources by provider" (drupal\modules\landlibrary\views\by_providers.inc) filters the Land Library Resources (LLR) that has as Data Provider (field_doc_provider) the organization selected.

https://landportal.info/organization/global-land-tool-network

It is wanted to change the contextual filter to on the organizational profiles not just where the organization is listed as ‘data provider’, but also ‘publisher’ or ‘corporate author'.

Drupal 7 contextual filters are applied in AND logic, and change to use OR logic is not be possible using the UI. 

Some hopefully helpful links:
http://stackoverflow.com/questions/13531828/drupal-7-views-contextual-filters-or-logic
https://www.drupal.org/project/views_contextual_filters_or
http://dropbucket.org/node/955

**Comment by lisettemeij** [comment]
Just wanted to add this again, but see it's already open here. Just want to give this issue a boost - it would be a relatively simple (I think), but great improvement.

**Comment by jcr** [comment]
Hi both,
Yes this have not been high on the list of priorities so far.
Nonetheless there is been some 'ground' work (related to LLR and Organization entity reference links) that should allow us to do those sort of things better now.

For this specific page / view you are talking about, we need to re-do the view using those new references.
In general the contextual filters in our views aren't very well implemented and the library ones (at least in 3, 4, maybe even 5 views?)  needs to be reviewed and maybe updated.
If this is not done correctly (specifically for the ones related to LLR-Organizations) this can have a huge impact on the DB performance (which is why I actually did some work on this just prior to the website update - around the team meeting in Roma).

@lisettemeij : yes it might seem trivial but no, it is not necessarily easy to do. Sometimes (most of the time) "simple things" to a human mind requires quite some work for a computer (that's maybe why they haven't turned all of us into slaves yet ;).

Once we update that we should be able to have much more accurate filters as well (only show possible options for instance...).

**Comment by aostroverkhov** [comment]
@jcr this is ready with the https://www.drupal.org/project/views_contextual_filters_or module now
(updated the make file)

**Comment by jcr** [comment]
fixed, on GLTN we now have 161
