### ISSUE TITLE
LLR preview - view messed up with several authors / publishers

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#156]
Hi all,

Can't find my old post which said that the logos shown in the preview should not be reduced to only "data provider" entries. But I'm pretty sure I put in there that in the case of several corporate authors or publishers, it should either show only 1 logo, or none at all. (please feel free to use your judgment on that).

In any case, now it screws up how the title shows up, see below:
<img width="1280" alt="screen shot 2016-10-27 at 13 18 01" src="https://cloud.githubusercontent.com/assets/6312043/19765400/7b59351a-9c48-11e6-8e52-92e32807be59.png">

Can we fix this?

**Comment by jcr** [comment]
note for the record - we need(ed) more proper spec + design for the LLR
teaser (+ I didn't forgot the full view also needed some love).

With the next LP theme we're going to have, we should have at the very
least 2 views for the teaser (and full page view):
1/ for medium size screens (laptop or small / medium size screens);
2/ for smaller devices;
3/ for larger screens (eventually - maybe just a medium + margins
otherwise);

best will be to start working on that on dev / the new version. Not
going to spend any second in production doing that (already explained to
Carlos how and why it's not worth spending hours or days fixing such
things on the current version)

J

**Comment by jcr** [comment]
this should not be messed up anymore (because we don't show them the same way on most display).
