### ISSUE TITLE
New Land Portal users not being added to Mailchimp newsletter list

### ISSUE THREAD

**Issue by lmeggiolaro** [landportal/drupal#159]
New Land Portal users are not being added to the Mailchimp newsletters. The sync is not working or does not exist as it did before. It appears to have stopped working in April 2016, and only worked for four months, from January - April 2016. This is a major problem.

**Comment by jcr** [comment]
It was discussed with Neil last week (or 2?) ago.

The Mailchimp related functionalities are temporarily unavailable due to
a major version bump on the module and their API.
Unfortunately the submodule that have been used by Ivo last year isn't
going to be continued so we have to take it on ourselves (redevelop /
make it compatible with the latest MC version). 

I am more surprised that this apparently stopped working in April?
This will be looked at before the end of this month as we need a plan to
make this work in the next 2-3months anyways (including lists
delegation).

**Comment by jcr** [comment]
the synchronization with Mailchimp is now working fine.
there will be more tickets / issues open to re-integrate list delegation
