### ISSUE TITLE
Search not working!

### ISSUE THREAD

**Issue by lmeggiolaro** [landportal/drupal#162]
I was going to include a screenshot, but it doesn't seem possible on Github. Anyway, the main search box doesn't work. I get the response "Search is temporarily unavailable. If the problem persists, please contact the site administrator."

**Comment by jcr** [comment]
yes it crashes intermittently since September.
Last week I changed the middle-ware running our search, which have improved the time it stays up but this it still not enough.
Do you remember, on top of your head how many days I can spend doing LP server and infrastructure work until the end of this year?

**Comment by jcr** [comment]
search should now be operational more than 99% of the time
still under close monitoring
