### ISSUE TITLE
Cache website slow? - Something delays new nodes (organizational profiles) show up in a form

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#164]
Hi,

I've been experiencing this problem when I add a LLR with a new publisher (so new organizational profile), it takes over half an hour before the organizational profile can be selected in the LLR form. This used to be something instantaneous.

When I mentioned this problem to Carlos, he cleared the cache and the profile showed up right away.

Vittoria mentioned it to me yesterday as well. The profiles used to show up instantaneously. This is a small thing, but really annoying because it means that you need to take about an hour to add a LLR.

And since it used to work before properly and I am not the only one experiencing this problem, can we please change this back? And let us know what exactly happened that this changed at all?

**Comment by jcr** [comment]
yes this special one is particularly longer than others.
This is because listing organizations are some of the most consuming queries. We need to get you a clear cache link , can you try to get to:
https://landportal.info/admin/config/development/performance
and use the clear all caches button if you can?

**Comment by jcr** [comment]
Last 2 weeks we found a few odd things with organization selections.
For now the cache should be disabled in the select lists (entity references).
