### ISSUE TITLE
Permissions not functioning

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#170]
Permissions are not functioning. Legend is unable to post items without approval, even though they could do this before. Also, contributors remain unable to post any information without approval.

**Comment by jcr** [comment]
FYI permissions ARE functioning otherwise everyone could do about anything with the portal.

You need to specify what content you are talking about specifically. It would also be useful to tell which account was involved or tested exactly.
Have you checked that it have the proper role (contributor)?

As you know permissions and roles were re-worked recently and should work accordingly to 
https://docs.google.com/document/d/1Hqac0wEZJtjMmlSXRlXjpr1vpmryF-RzKJcBj0AJVlo/edit#heading=h.bnu1ejp7g56c

**Comment by jcr** [comment]
https://landportal.info/admin/config/workflow/rules/reaction/manage/rules_publish_contrib updated

 - to be tested: contributors publish directly (they actually don't have a choice to save as draft :s) blogs, LLR, events and News
 - rule not baked in code

**Comment by jcr** [comment]
Rechecked and tested.
Permissions seems consistent with
https://docs.google.com/document/d/1Hqac0wEZJtjMmlSXRlXjpr1vpmryF-RzKJcBj0AJVlo/edit#heading=h.ci6ul2f4w2hm
For the record, rules to manage publications status are 
https://landportal.info/admin/config/workflow/rules
(publish contrib and unpublished content) and baked in landportal_admin module.
emails alert are sent on every content creation from non-LP users.
