### ISSUE TITLE
"towards a protocol on fair compensation" thumbnail is showing up as the thumbnail for other publications on Land Library

### ISSUE THREAD

**Issue by ntagliar** [landportal/drupal#175]
![screen shot 2016-11-30 at 10 47 52 pm](https://cloud.githubusercontent.com/assets/24232810/20773102/7ba00fe4-b750-11e6-968e-dc53a43cf2f1.png)

**Comment by ntagliar** [comment]
I think I may have fixed by deleting the thumbnail, but could someone verify?

**Comment by jcr** [comment]
I am not sure how adding a thumbnail to an LLR could have had such side effects.
where have you seen it replace other thumbnails? on which page?
What do you mean by "I may have fixed by deleting the thumbnail" ?
http://landportal.info/node/37504/edit is still using that picture. To me it all seems ok.

feel free to re-open this ticket if needed.

**Comment by ntagliar** [comment]
I think (when I uploaded a new Land Library resources yesterday) the thumbnail I added attached to all documents that had "No Thumbnail available". So I went to "content"---then thumbnails---and deleted the thumbnail I added. This took that thumbnail off of all the documents that previously had no thumbnails.

**Comment by ntagliar** [comment]
I'll keep looking to see if the thumbnail is misplaced on other Land Library resources, but as far as I'm aware, the problem is fixed
