### ISSUE TITLE
Calendar items in events in nonsensical order

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#184]
As mentioned on many occasions since 2015, the calendar of events lists events in a nonsensical order, with events furthest in the future coming first, going backward to events that are shortly approaching, followed by recently past events.

The standard is for events that are shortly approaching to appear first followed by those taking place further in the future, with past events separated as 'Past Events, or something similar, beginning with the most recent past events, and going further into the past.

**Comment by jcr** [comment]
ACK.
This works as it was originally intended. We have one list that shows events from the further-est date to the oldest one.
AFAIR on the 'nonsensical' order you mention there was also an issue with some sticky events published that were messing up the order and/or issues with languages as well.

To be constructive (I think we discussed that already), in order to improve that we want to have 2 lists.
One for upcoming events and another one for past events.
Also we will/should re-enable a calendar like widget.

**Comment by realneilsorensen** [comment]
I've always said this makes no sense. I've never in my entire career seen a calendar function in this way.

**Comment by dayures** [comment]
related to #28
