### ISSUE TITLE
Country narrative nodes - fix titles + link to CP (portfolio)

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#204]
https://landportal.info/book/countries/afganistan

These are country pages related to a "country narrative"

**Comment by jcr** [comment]
So I give a fair amount of though into this and it's not true. - so updating the title.

What need to be done is:
1/ fold them into date space
2/ to show prominently on the page that this isn't the "latest" narrative.

**Comment by jcr** [comment]
1/ done - folded under book/narratives/YEAR/countries-XXX
so they don't have the CP blocks (empty otherwise)
situation still not perfect (those page miss a title, for witch we should integrate region/country terms to render as the header of country narrative CT -like on TPs-)

for the link to the proper country page, maybe adding a block that shows on Country narrative CT when NOT showing under the /book/countries/XXX path.

**Comment by jcr** [comment]
all done and clean
