### ISSUE TITLE
Display issue on LandVoc page

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#216]
Hi all,

I'm noticing that with the new responsiveness design for the pages, many views are looking pretty awful. Found another one on the LandVoc page for the themes (see below). The images are tiny, basically can't be seen properly + the text in such a narrow column basically makes it unreadable.

<img width="1280" alt="screen shot 2017-01-23 at 15 07 05" src="https://cloud.githubusercontent.com/assets/6312043/22207026/d1b29f9e-e17d-11e6-8831-f4a0941fb971.png">

Can we fix this?

**Comment by jcr** [comment]
2 issues here:
1/ description in taxonomies can't be trimmed (like with node content / teasers). - maybe improve later
2/ in those terms someone entered a narrative rather than a definition.

Corrective action: hide all description for now.
of course it can still be improved but first we need a plan and a design
