### ISSUE TITLE
Form to add content doesn't work properly in Safari

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#24]
If you add content in a Safari browser, there are a lot of tiny annoying errors. If you press enter, the enter appears on top of the content (even if you're at the end). Often you can't select text because the whole screen moves completely up or down and you have to scroll back to the text.

I don't have these errors in Chrome or Firefox, so I usually switch browser to add something. But that shouldn't be necessary, right? Any idea what this could be?

**Comment by jcr** [comment]
hey lisette, this is rather old.

From what I understood it was an issue with the rich text editor (tinymce).
Have you tried using it with the full screen/maximize option (next to source)?

I'll mark this as won't fix because this is likely a much broader issue between Safari and Drupal/tinymce (our wysiwyg editor).
I would be good if we could test it on another drupal site that also have this rich text editor and see if that works.
