### ISSUE TITLE
Promoted to country page feature isn't working

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#281]
Hi,

The promoted to country page feature isn't working anymore. It doesn't give you the field to select the country where the resource should be promoted to:

![screen shot 2017-04-10 at 10 25 06](https://cloud.githubusercontent.com/assets/6312043/24852503/0d085e3a-1dd8-11e7-9638-4c7aeab5aaa4.png)

Can we get this back ASAP? Thanks!

**Comment by jcr** [comment]
ah no this was actually changed a while back (in agreement with Laura and it was , AFAIR, linked with a chat discussions when we released more portfolios).
In order to have less 'empty' countries pages, when promoting content to CP, it's the geo tag that makes the node appear on the CP.
Re-open if this really is not working (ie: if a content is promoted to a CP, have a geo tag for the country and does not appear there)
