### ISSUE TITLE
Require Terms and Conditions approval from user

### ISSUE THREAD

**Issue by jcr** [landportal/drupal#361]
from Lisette's email (31 august)
"Terms and Conditions of use for Users should be more prominent"

So we propose to steps:
add a tick box to agree with the T&C of the Portal (mandatory field);
add a sentence in the confirmation email that they agreed to the T&C and should read it carefully before contributing.

+ link to the T&C next to add/create new content buttons

**Comment by lisettemeij** [comment]
Thanks for putting this on Github!

Instead of a sentence in the confirmation email though, I would put the sentence close to the 'save'/'preview'/'publish' buttons. So even before they put something online, they are aware that this has consequences. 

Afterwards, it a weaker message and people would be less inclined to go and change something or think it over -- they already published the whole thing.
