### ISSUE TITLE
VERY URGENT: CONNECTION WITH MAILCHIMP NOTWORKING - NOT REQUIRING GEOGRAPHIC LOCATION

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#372]
The connection with Mailchimp for account and newsletter signups does not seem to be working. I have reported this many times. Also, we must require geographic location of Land Portal and Mailchimp users, as we did before, as this is something we have to track for our donors and is critical.

**Comment by jcr** [comment]
There are 2 "issues" in this:

1. the "not requiring geographic location" - which should be mandatory to register to the Land Portal Newsletter (where the point is to be able to give stats on the reader's country of residency / or nationality?).

it was agreed (approved by Laura) to disable temporarily this parameter on MC so it would not result in error on the Land Portal side until this is fixed properly (which will be on the work for user profiles https://github.com/landportal/drupal/milestone/18).
On the MC side the field is as 'free text' field which is not ideal as it's not a controlled information.
On Drupal the issue is that the MailChimp module (pristine one), isn't capable of linking the geographical field to the MC list fields (anymore?). Altogether we will re-implement a solution that will re-allow this to work properly (ETA: before end of Nov.).
Note that on Mailchimp it would be a good idea to cleanup all the fields (wrongly added?) to the Newsletter subscribers (in MC > List LP Newsletter > Settings 

2. on "connection with mailchimp notworking" it would be good if you could elaborate a bit more. As you mentioned it has been asked and also fixed a while ago, adding also other 'automated' lists (Land Portal Users)
AFAIK, Carlos even tested that no later than yesterday and successfully:
 - created an account on LP > it subscribed to the Land Portal Newsletter list on MC
 - unsubscribed from the list (LP) > it updated his user status on LP and MC as not Subscribed.
 - subscribe from LP (again but through the user edit) > re-added on MC side
 - unsubscribing from MC side didn't reflected the changes on the LP. I found out that some settings on the LP where disabled (? - I don't know how). Being related to the synchronization of the list I re-enabled that and tested it again from the MC side (subscribing or unsubscribing a list) and is now properly linked to the user account. Altogether that last point was a bit more trivial but maybe have resulted in some warning messages show on the site.

Now, if you have more specific situation and use cases where you suspect something didn't happened properly to describe and email address or user names to provide that would be helpful.

If not, please close the ticket as we now have one specific for the country issue (https://github.com/landportal/drupal/issues/374).

ps: ALL CAPS is not appropriate for a title. And, again, notifications you consider urgent needs to also be notified in mail and/or chat.

**Comment by jcr** [comment]
fixed, already working on live site
