### ISSUE TITLE
Promote to country page option does not work

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#440]
Hi,

I just tried to promote the following publication to the country pages it is tagged with:

https://landportal.org/library/resources/women-and-land-muslim-world

But it does not show up on the country pages it is linked with, e.g.:

https://landportal.org/voc/regions/egypt
https://landportal.org/voc/regions/niger
https://landportal.org/voc/regions/morocco
https://landportal.org/voc/regions/afghanistan

It did work with front page, thematic page and library page. Any thoughts? 

This option should work and as I mentioned before, ideally it should not automatically be promoted to ALL country pages it is tagged with (some countries have less content so we need to promote less valuable resources, that we don't necessarily want on each page). For this publication, it should be promoted to all countries.

Thanks,
Lisette

**Comment by jcr** [comment]
Those options (other promoted than the base drupal one) have not been used since last summer. AFAIR, it was something quickly discussed during the early summer team meeting to anticipate the new content structure. Then, when we added some new country pages - Laura did formally confirmed  we would show all resources related/tagged .

Nonetheless, you're right, we need to be able to promote something on a _specific type_ of page without having those resources showing up on the LP front page.
For now, I have temporarily fixed the related content views that were missing this sort criteria. So we now have the publications that are promoted on front page first, then by date of publication (real).

I will re-add an option -probably slightly different than the too specific one we had before- to be able to choose where this should be promoted (eg: on narrative pages, on data/indicators pages etc...) and adapt the views that need to work this way (we have for the new site).
