### ISSUE TITLE
Problem with Mailchimp connection / newsletter signup

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#472]
There remains a problem with the newsletter signup feature when creating profiles on the Land Portal. They are supposed to automatically connect with Mailchimp and update the Mailchimp list. This has been a problem for many months, if not years. I don't know how many new profiles have not been synced with Mailchimp, probably a great many.

See screenshot below. 'There was a problem with the newsletter sign up'.

![image](https://user-images.githubusercontent.com/23736268/41960657-a047b8e2-79f0-11e8-9ae8-2746f72d8a2f.png)

**Comment by asanchez75** [comment]
> The Mailchimp list of users is not complete - there are 2612 Land Portal users, and the Mailchimp list has 1618. I do not know how to explain the discrepancy.

**Comment by realneilsorensen** [comment]
There continues to be the  same problem as mentioned three weeks ago: 

![image](https://user-images.githubusercontent.com/23736268/42868447-9d4b9c70-8a72-11e8-8df5-409c362d7541.png)

**Comment by asanchez75** [comment]
Finally, I have identified the problem.
Each time a new user subcribes to a landportal mailing list (during the registration process), Mailchimp verifies if the submitted data contains these three fields (FNAME, LNAME, CLIST) with their respective values. If not, Mailchimp rejects the subscription with an internal message like 

```
An error occurred subscribing h.sanchez75@gmail.com to list 8b8de3bf56. Status code 400. "400: Invalid Resource - Your merge fields were invalid. a:3:{i:0;O:8:"stdClass":2:{s:5:"field";s:5:"FNAME";s:7:"message";s:20:"Please enter a value";}i:1;O:8:"stdClass":2:{s:5:"field";s:5:"LNAME";s:7:"message";s:20:"Please enter a value";}i:2;O:8:"stdClass":2:{s:5:"field";s:5:"CLIST";s:7:"message";s:20:"Please enter a value";}}"

```
The bug is that Drupal does not include the value for these three fields despite of these fields were filled out by the user.

I am working on fixing.

**Comment by asanchez75** [comment]
#### Updates
I fixed the automatic subscription. When an user creates an account, the user is also subscribed to a Mailchimp list. However, I must check now the set of Drupal rules because the Mailchimp list chosen by the user is not preserved in its account information. It seems overriden by some rule configured to trigger some events once a user is registered.

For the record I paste here the code I wrote to fix this.

```
<?php

/**
 * Alter mergevars before they are sent to MailChimp.
 *
 * @param array $mergevars
 *   Array of MailChimp mergevars.
 * @param object $entity
 *   The entity used as a source for mergevar values.
 * @param string $entity_type
 *   The type of entity used as a source for mergevar values.
 * @param string $list_id
 *   The ID of the MailChimp list containing the mergevars.
 */

function landportal_mailchimp_signup_mailchimp_lists_mergevars_alter(&$mergevars, $entity, $entity_type, $list_id) {
  $mergevars1 = mailchimp_get_mergevars(array($list_id));
  $mergevars['FNAME'] = $entity->profile_main['field_firstname'][LANGUAGE_NONE][0]['value'];
  $mergevars['LNAME'] = $entity->profile_main['field_lastname'][LANGUAGE_NONE][0]['value'];
  $mergevars['CLIST'] = location_country_name($entity->profile_main['field_location'][LANGUAGE_NONE][0]['country']);
}

```

**Comment by asanchez75** [comment]
Fixed. please, test it and if works please close this ticket.
