### ISSUE TITLE
Library resource type page - hierarchy taxonomy view

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#498]
Hi,

The taxonomy view for LLR type on this page:

https://landportal.org/library/resource-type

should be shown with its hierarchy (so the categories make sense). This is the case when I'm logged in:

<img width="419" alt="screenshot 2019-01-21 at 13 53 59" src="https://user-images.githubusercontent.com/6312043/51475877-051a2980-1d84-11e9-835a-3051c39af178.png">

But not when I'm logged out:

<img width="440" alt="screenshot 2019-01-21 at 13 54 29" src="https://user-images.githubusercontent.com/6312043/51475902-16633600-1d84-11e9-8746-5248d043ff8d.png">

Naturally, this should be consistent. Can we please make sure the hierarchy is ALWAYS shown, regardless of whether we're logged in or not?

Thanks!

**Comment by lisettemeij** [comment]
Also, can we please make sure the description of each taxonomy concept also appears in this view?

It was deleted after we put this into a hierarchy view.

Thanks!

**Comment by silvinabcn** [comment]
Hi @lisettemeij 
I fixed the anonymous view (now it shows as a tree as well) and I added the description for each category. Is this OK or would your prefer to crop the description and to display less text? Please let me know. Thanks.

@asanchez75 FYI: I added the field "Taxonomy term: Term description" and set it as inline in the format section (fields). To fix the tree for anonymous visitors, I disabled SQL rewriting.

**Comment by lisettemeij** [comment]
Hi @silvinabcn, thanks so much for this! Wow, it is a lot of text with the description, haha. If it's possible to crop the text (and unfold or something if you click?), then yes, please, I think that would make the page much less scary ;-)

**Comment by silvinabcn** [comment]
hi @lisettemeij 
please check it on https://dev.landportal.org/library/resource-type
I set it  to crop the description on 160 characters (always on full words), to add 3 point (...) and the word 'more' linking to the term page.
I can change the amount of characters, add/remove the elipsis, and use any text you prefer instead of more (or none at all). I tested 120 characters and this is only one line in external PC screens (I don't have a laptop to test).
What do you think? Is this too crop/too long? Do you want me to test other configurations?

**Comment by squinternata** [comment]
Hi all,
sorry I don t know why I am received this thread even if I am not subscribed.
could you please check if my email is somewhere? thanks
A

**Comment by lisettemeij** [comment]
hi @silvinabcn Thanks for your quick response to this! The crop indeed may be shortened to 100-120 characters in my opinion, the 'more' link is very clear. Only when I click on the link I get a 404 error, is that because it's on dev still right now?

Any idea on how we can remove @squinternata from this conversation? Very sorry that you're getting notifications!! I don't know why either. we will look into it, for sure.

**Comment by silvinabcn** [comment]
Hi @lisettemeij 
I edited your comment and removed the "@" from  squinternata because mentioning him will add him (or her) again to this issue. I don't know how come he got the notification in the first place :(

Regarding the page, I cropped the text to 120 characters and fixed the 'more' link (it was my mistake). 
I applied this change to both DEV and PROD sites. 
Please let me know if this is OK and we can close the issue or if I should do further changes. Thanks.

**Comment by lisettemeij** [comment]
Hi Silvina,

This all looks great, thanks so much!  We can close the issue as far as I'm concerned :)

Thanks for your quick action!

Best,
Lisette
