### ISSUE TITLE
Spanish news item can only be displayed as English

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#63]
Hi all,

This Spanish news items appears on the English interface: https://landportal.info/news/2016/05/cinco-razones-por-las-que-la-juventud-deber%C3%ADa-optar-por-la-agricultura. I unpublished it for now.

I tried to change the language to Spanish on the bottom of the page, but it does not appear in the dropdown menu for some reason.

If I try to add a new news item, that drop down menu does seem to work.

Any ideas?

**Comment by jcr** [comment]
It happened because this content was created as an English one (and you cannot change this afterwards, maybe that's the thing to be changed here)
https://landportal.info/node/30342/translate

How to fix it?
 re-create the news, this time using Spanish, then remove this one.
OR (maybe?)
 create a translation for this news in Spanish (link above) and remove/leave the English one un-publish.

The issue here seems more to be the human/keyboard interface.

**Comment by lisettemeij** [comment]
Ok good, I'll take care of that then.

Thanks Jules!
