### ISSUE TITLE
Contact form doesn't work in other language interface

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#68]
The contact form disappears in the other language interfaces:

https://landportal.info/fr/node/30375

**Comment by jcr** [comment]
I think you just need to 'translate' this page? I will give it a try later

**Comment by jcr** [comment]
turns out the contact page was simply not translated.
I did that for french it works as expected : https://landportal.info/fr/contact-us
1. click on translate button
2. create the page for language X
3. give your page 'contact-us' as a publication path (so the contact form appear and urls are consistent)

**Comment by dayures** [comment]
Added Spanish translation

**Comment by dayures** [comment]
@jcr is it possible to i18n the form itself?

**Comment by jcr** [comment]
currently works on all 4 languages
