### ISSUE TITLE
Autocomplete content type forms

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#93]
The autocomplete fields for the forms to create a content type (news, blogs, events) have disappeared and are now suddenly lists. (see screenshot attached). Which is not what we want, because:
- the window is super small so you can't see a lot of options and scrolling through is a nightmare
- the lists are too long to scroll through, nobody will ever get to the bottom
- it is a nightmare to select more than 1 concept for example. Definitely not desirable. 

Can we change it back to the old autocomplete forms please?

![screen shot 2016-07-04 at 14 14 30](https://cloud.githubusercontent.com/assets/6312043/16560164/ee3f26ea-41f1-11e6-8e9e-5fd73a3fa35e.png)

**Comment by jcr** [comment]
hot fixed in production.
choosen field selection at https://landportal.info/admin/config/user-interface/chosen
should be something more general like : " .search-form .form-select,.node-form .form-select,.taxonomy-form-term .form-select "
As this setting is more than just the search (general LP UI) - it should probably not be in this feature but maybe in a more general UI module/feature.

**Comment by aostroverkhov** [comment]
@jcr ok will check this out

**Comment by aostroverkhov** [comment]
@jcr this is ready now, tested on dev - https://github.com/landportal/drupal/commit/bb26fe49e728bbf9a3ceef4f30ff949139cd9b88
